Update proton_run.yml

diff --git a/.github/workflows/proton_run.yml b/.github/workflows/proton_run.yml
--- a/.github/workflows/proton_run.yml
+++ b/.github/workflows/proton_run.yml
@@ -30,7 +30,6 @@ jobs:
       target_region: ${{ steps.get-data.outputs.target_region }}
       proton_region: ${{ steps.get-data.outputs.proton_region }}
       state_bucket: ${{ steps.get-data.outputs.state_bucket }}
-      is_deleted: ${{ steps.get-data.outputs.is_deleted }}
     
     permissions:
       id-token: write
@@ -42,13 +41,6 @@ jobs:
     # Checkout the repository to the GitHub Actions runner
     - name: Checkout
       uses: actions/checkout@v2
-      
-    - name: Verify env_config updated
-      run: |
-        if grep -q REPLACE_ME env_config.json; then
-          echo "You must update env_config.json or update this workflow to not require it."
-          exit 1
-        fi
       
     - name: Get changed files
       id: files
@@ -81,7 +73,6 @@ jobs:
       run: |
         modified_resource_arn=$(jq -r '.resourceMetadata.arn' ${{ steps.find-modified.outputs.deployment-metadata-path }})
         echo "::set-output name=resource_arn::$modified_resource_arn"
-        echo $resource_arn
         
         IFS=':'
         read -a split_arn <<< "$modified_resource_arn"
@@ -90,10 +81,6 @@ jobs:
 
         deployment_id=$(jq -r '.deploymentId' ${{ steps.find-modified.outputs.deployment-metadata-path }})
         echo "::set-output name=deployment_id::$deployment_id"
-
-        is_deleted=$(jq -r '.isResourceDeleted' ${{ steps.find-modified.outputs.deployment-metadata-path }})
-        echo "::set-output name=is_deleted::$is_deleted"
-
 
         if [[ "$modified_resource_arn" == *":environment/"* ]]; then
           environment_name=${modified_resource_arn##*/}
@@ -122,25 +109,21 @@ jobs:
           working_directory=pipeline/$service_name
         fi
 
-        if [[ $(jq -r --arg env $environment_name 'has($env)' env_config.json) = "true" ]]; then
-          role_arn=$(jq -r --arg env $environment_name '.[$env]["role"]' env_config.json)
-          target_region=$(jq -r --arg env $environment_name '.[$env]["region"]' env_config.json)
-          state_bucket=$(jq -r --arg env $environment_name '.[$env]["state_bucket"]' env_config.json)
-        else     
-          if [[ $(jq -r --arg env $environment_name 'has("*")' env_config.json) = "true" ]]; then
-            role_arn=$(jq -r --arg env $environment_name '.["*"]["role"]' env_config.json)
-            target_region=$(jq -r --arg env $environment_name '.["*"]["region"]' env_config.json)
-            state_bucket=$(jq -r --arg env $environment_name '.["*"]["state_bucket"]' env_config.json)
-          else
-            echo "Missing $environment_name or * from env_config.json, exiting"
-            exit 1
-          fi
+        if [[ $(jq -r --arg env $environment_name 'has($env)' env_config.json) = "false" ]]; then
+          echo "Missing $env from env_config.json, existing"
+          exit 1
         fi
-        
+
         echo "::set-output name=working_directory::$working_directory"
         echo "::set-output name=environment::$environment_name"
+        
+        role_arn=$(jq -r --arg env $environment_name '.[$env]["role"]' env_config.json)
         echo "::set-output name=role_arn::$role_arn"
+
+        target_region=$(jq -r --arg env $environment_name '.[$env]["region"]' env_config.json)
         echo "::set-output name=target_region::$target_region"
+
+        state_bucket=$(jq -r --arg env $environment_name '.[$env]["state_bucket"]' env_config.json)
         echo "::set-output name=state_bucket::$state_bucket"
 
   terraform:
@@ -148,6 +131,9 @@ jobs:
     needs: get-deployment-data
     runs-on: ubuntu-latest
     environment: ${{ needs.get-deployment-data.outputs.environment }}
+
+    outputs:
+      tf_outputs: ${{ steps.tf_get_outputs.outputs.tf_outputs }}
 
     permissions:
       id-token: write
@@ -158,10 +144,8 @@ jobs:
         working-directory: ${{ needs.get-deployment-data.outputs.working_directory }}
         shell: bash # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
 
-    if: needs.get-deployment-data.result == 'success' && needs.get-deployment-data.outputs.is_deleted == 'false'
-
-    outputs:
-      success: ${{ steps.mark_success.outputs.success }}
+    if: needs.get-deployment-data.result == 'success'
+    continue-on-error: true
 
     steps:
     # Checkout the repository to the GitHub Actions runner
@@ -175,8 +159,7 @@ jobs:
         aws-region: ${{ needs.get-deployment-data.outputs.target_region }}
         role-to-assume: ${{ needs.get-deployment-data.outputs.role_arn }}
         role-session-name: TF-Github-Actions
-        mask-aws-account-id: 'no'
-        
+
     # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
     - name: Setup Terraform
       id: tf_setup
@@ -206,11 +189,20 @@ jobs:
       id: tf_apply
       if: github.ref == 'refs/heads/main' && github.event_name == 'push'
       run: terraform apply -auto-approve -var="aws_region=${{ needs.get-deployment-data.outputs.target_region }}"
-    
-    # If this completes, then the entire workflow has successfully completed
-    - name: Mark Success
-      id: mark_success
-      run: echo "::set-output name=success::True"
+
+    - name: Terraform Get Outputs
+      id: tf_get_outputs
+      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
+      run: |
+        # Get outputs as json
+        outputs_json=$(terraform output -json)
+
+        # The outputs parameters expects a list of key=keyName,valueString=value key=key2Name,valueString=value2 etc...
+        # So here we convert the output json into a shell array
+        # NOTE: This will probably not play nicely with complex output objects (non primitives)
+
+        formatted_outputs=( $(echo $outputs_json | jq -r "to_entries|map(\"key=\(.key),valueString=\(.value.value|tostring)\")|.[]") )
+        echo "::set-output name=tf_outputs::$formatted_outputs"
 
   notify-proton:
     name: 'Notify Proton'
@@ -220,99 +212,37 @@ jobs:
     runs-on: ubuntu-latest
     environment: ${{ needs.get-deployment-data.outputs.environment }}
 
-    if: github.event_name == 'push' && github.ref == 'refs/heads/main' && needs.get-deployment-data.outputs.is_deleted == 'false'
+    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
     
     permissions:
       id-token: write
       contents: read
-      
-    defaults:
-      run:
-        working-directory: ${{ needs.get-deployment-data.outputs.working_directory }}
-        shell: bash # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
 
     steps:
-    # Checkout the repository to the GitHub Actions runner
-    - name: Checkout
-      uses: actions/checkout@v2
-      
     - name: Configure AWS Credentials
       id: assume_role
       uses: aws-actions/configure-aws-credentials@v1
       with:
-        aws-region: ${{ needs.get-deployment-data.outputs.target_region }}
+        aws-region: ${{ needs.get-deployment-data.outputs.proton_region }}
         role-to-assume: ${{ needs.get-deployment-data.outputs.role_arn }}
         role-session-name: TF-Github-Actions-Notify-Proton
-        mask-aws-account-id: 'no'
-        
-    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
-    - name: Terraform Init
-      id: tf_init
-      continue-on-error: true
-      run: terraform init -backend-config="bucket=${{ needs.get-deployment-data.outputs.state_bucket }}" -backend-config="key=${{ needs.get-deployment-data.outputs.working_directory }}terraform.tfstate" -backend-config="region=${{ needs.get-deployment-data.outputs.target_region }}"
+      
+    # This is a temporary measure until this feature exits Public Preview
+    - name: Install Proton Model
+      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
+      run: |
+        aws s3 cp s3://aws-proton-preview-public-files/model/proton-2020-07-20.normal.json  .
 
     - name: Notify Proton Success
       id: notify_success
-      if: needs.terraform.outputs.success == 'True' && steps.tf_init.outcome == 'success'
+      if: needs.terraform.result == 'success'
       run: |
-        # Get outputs as json
-        outputs_json=$(terraform output -json)
-        
-        # The outputs parameters expects a list of key=keyName,valueString=value key=key2Name,valueString=value2 etc...
-        # So here we convert the output json into a shell array
-        # NOTE: This will probably not play nicely with complex output objects (non primitives)
-
-        formatted_outputs=( $(echo $outputs_json | jq -r "to_entries|map(\"key=\(.key),valueString=\(.value.value|tostring)\")|.[]") )
-        
-        # Notify proton
-        aws proton notify-resource-deployment-status-change --region ${{ needs.get-deployment-data.outputs.proton_region }} --resource-arn ${{ needs.get-deployment-data.outputs.resource_arn }} --status SUCCEEDED --deployment-id ${{ needs.get-deployment-data.outputs.deployment_id }} --outputs ${formatted_outputs[*]}
+       # Notify proton
+        aws proton notify-resource-deployment-status-change --region ${{ needs.get-deployment-data.outputs.proton_region }} --resource-arn ${{ needs.get-deployment-data.outputs.resource_arn }} --status SUCCEEDED --deployment-id ${{ needs.get-deployment-data.outputs.deployment_id }} --outputs ${{ needs.terraform.outputs.tf_outputs }}
         echo "Notify success!"   
         
     - name: Notify Proton Failure
-      if: needs.terraform.outputs.success != 'True' || steps.tf_init.outcome != 'success'
+      if: needs.terraform.result == 'failure' || needs.terraform.result == 'cancelled'
       run: |
         aws proton notify-resource-deployment-status-change --region ${{ needs.get-deployment-data.outputs.proton_region }} --resource-arn ${{ needs.get-deployment-data.outputs.resource_arn }} --status FAILED --deployment-id ${{ needs.get-deployment-data.outputs.deployment_id }}
         echo "Notify failure!"
-
-  terraform-destroy:
-    name: 'Run terraform destroy'
-    needs: 
-    - get-deployment-data
-    runs-on: ubuntu-latest
-    environment: ${{ needs.get-deployment-data.outputs.environment }}
-
-    if: github.event_name == 'push' && github.ref == 'refs/heads/main' && needs.get-deployment-data.outputs.is_deleted == 'true'
-    
-    permissions:
-      id-token: write
-      contents: read
-      
-    defaults:
-      run:
-        working-directory: ${{ needs.get-deployment-data.outputs.working_directory }}
-        shell: bash # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
-
-    steps:
-    # Checkout the repository to the GitHub Actions runner
-    - name: Checkout
-      uses: actions/checkout@v2
-      
-    - name: Configure AWS Credentials
-      id: assume_role
-      uses: aws-actions/configure-aws-credentials@v1
-      with:
-        aws-region: ${{ needs.get-deployment-data.outputs.target_region }}
-        role-to-assume: ${{ needs.get-deployment-data.outputs.role_arn }}
-        role-session-name: TF-Github-Actions-Notify-Proton
-        mask-aws-account-id: 'no'
-
-    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
-    - name: Terraform Init
-      id: tf_init
-      continue-on-error: true
-      run: terraform init -backend-config="bucket=${{ needs.get-deployment-data.outputs.state_bucket }}" -backend-config="key=${{ needs.get-deployment-data.outputs.working_directory }}terraform.tfstate" -backend-config="region=${{ needs.get-deployment-data.outputs.target_region }}"
-    
-    - name: Terraform Destroy
-      id: tf_destroy
-      run: terraform apply -auto-approve -destroy -var="aws_region=${{ needs.get-deployment-data.outputs.target_region }}"
-
